# Generated by Django 2.2.10 on 2020-03-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, null=True)),
                ('event', models.CharField(max_length=50, null=True)),
                ('nr_of_tickets_bought', models.IntegerField(null=True)),
                ('original_price', models.IntegerField(null=True)),
            ],
        ),
    ]
