# Generated by Django 2.2.10 on 2020-03-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='profit',
            field=models.IntegerField(null=True),
        ),
    ]
