# Generated by Django 2.2.10 on 2020-03-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_purchase_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='current_price',
            field=models.IntegerField(null=True),
        ),
    ]
